///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace hepsiburada
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The addToWish recording.
    /// </summary>
    [TestModule("5e8a9754-c1d0-495f-95de-0eba21e54297", ModuleType.Recording, 1)]
    public partial class addToWish : ITestModule
    {
        /// <summary>
        /// Holds an instance of the hepsiburadaRepository repository.
        /// </summary>
        public static hepsiburadaRepository repo = hepsiburadaRepository.Instance;

        static addToWish instance = new addToWish();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public addToWish()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static addToWish Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SomeSpanTag' at 32;4.", repo.ApplicationUnderTest.SomeSpanTagInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.SomeSpanTag.Click("32;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.UlTag1.SomeSvgTag1' at 19;8.", repo.ApplicationUnderTest.UlTag1.SomeSvgTag1Info, new RecordItemIndex(1));
            repo.ApplicationUnderTest.UlTag1.SomeSvgTag1.Click("19;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.UlTag1.SomeSvgTag2' at 1062;293.", repo.ApplicationUnderTest.UlTag1.SomeSvgTag2Info, new RecordItemIndex(2));
            repo.ApplicationUnderTest.UlTag1.SomeSvgTag2.MoveTo("1062;293");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.UlTag1.SomeSvgTag2' at 1228;326.", repo.ApplicationUnderTest.UlTag1.SomeSvgTag2Info, new RecordItemIndex(3));
            repo.ApplicationUnderTest.UlTag1.SomeSvgTag2.MoveTo("1228;326");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.UlTag1.SomeSvgTag3' at 11;5.", repo.ApplicationUnderTest.UlTag1.SomeSvgTag3Info, new RecordItemIndex(4));
            repo.ApplicationUnderTest.UlTag1.SomeSvgTag3.MoveTo("11;5");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'ApplicationUnderTest.UlTag1.SomeSvgTag3' at 19;-3.", repo.ApplicationUnderTest.UlTag1.SomeSvgTag3Info, new RecordItemIndex(5));
            repo.ApplicationUnderTest.UlTag1.SomeSvgTag3.MoveTo("19;-3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.UlTag1.SomePathTag' at 7;18.", repo.ApplicationUnderTest.UlTag1.SomePathTagInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.UlTag1.SomePathTag.MoveTo("7;18");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ApplicationUnderTest.UlTag1.SomePathTag1' at 1491;548.", repo.ApplicationUnderTest.UlTag1.SomePathTag1Info, new RecordItemIndex(7));
            repo.ApplicationUnderTest.UlTag1.SomePathTag1.MoveTo("1491;548");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest.UlTag1.SomePathTag1' at 1283;432.", repo.ApplicationUnderTest.UlTag1.SomePathTag1Info, new RecordItemIndex(8));
            repo.ApplicationUnderTest.UlTag1.SomePathTag1.MoveTo("1283;432");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -120 units.", new RecordItemIndex(9));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 240 units.", new RecordItemIndex(10));
            Mouse.ScrollWheel(240);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(11));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Beğendiklerim' at 115;6.", repo.ApplicationUnderTest.BeğendiklerimInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.Beğendiklerim.Click("115;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (SafeClass='my-list-info') on item 'ListemHepsiburada.MyListMain.MyListInfo'.", repo.ListemHepsiburada.MyListMain.MyListInfoInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.ListemHepsiburada.MyListMain.MyListInfoInfo, "SafeClass", "my-list-info");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ListemHepsiburada.MyListMain.ProductView'.", repo.ListemHepsiburada.MyListMain.ProductViewInfo, new RecordItemIndex(14));
            Validate.Exists(repo.ListemHepsiburada.MyListMain.ProductViewInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 120 units.", new RecordItemIndex(15));
            Mouse.ScrollWheel(120);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ListemHepsiburada.MyListMain.SomePathTag' at 88;4.", repo.ListemHepsiburada.MyListMain.SomePathTagInfo, new RecordItemIndex(16));
            repo.ListemHepsiburada.MyListMain.SomePathTag.Click("88;4");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
