///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace hepsiburada
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the hepsiburadaRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("56b5bbbe-466b-4c6c-bdc1-be13c0197d6b")]
    public partial class hepsiburadaRepository : RepoGenBaseFolder
    {
        static hepsiburadaRepository instance = new hepsiburadaRepository();
        hepsiburadaRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        hepsiburadaRepositoryFolders.TuerkiyeninEnBueyuekOnlineAlışverişAppFolder _tuerkiyeninenbueyuekonlinealışveriş;
        hepsiburadaRepositoryFolders.UEyeGirişSayfasıUEyeOlHepsiburadAppFolder _ueyegirişsayfasıueyeolhepsiburad;
        hepsiburadaRepositoryFolders.ListemHepsiburadaAppFolder _listemhepsiburada;
        hepsiburadaRepositoryFolders.SepetimAppFolder _sepetim;

        /// <summary>
        /// Gets the singleton class instance representing the hepsiburadaRepository element repository.
        /// </summary>
        [RepositoryFolder("56b5bbbe-466b-4c6c-bdc1-be13c0197d6b")]
        public static hepsiburadaRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public hepsiburadaRepository() 
            : base("hepsiburadaRepository", "/", null, 0, false, "56b5bbbe-466b-4c6c-bdc1-be13c0197d6b", ".\\RepositoryImages\\hepsiburadaRepository56b5bbbe.rximgres")
        {
            _applicationundertest = new hepsiburadaRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _tuerkiyeninenbueyuekonlinealışveriş = new hepsiburadaRepositoryFolders.TuerkiyeninEnBueyuekOnlineAlışverişAppFolder(this);
            _ueyegirişsayfasıueyeolhepsiburad = new hepsiburadaRepositoryFolders.UEyeGirişSayfasıUEyeOlHepsiburadAppFolder(this);
            _listemhepsiburada = new hepsiburadaRepositoryFolders.ListemHepsiburadaAppFolder(this);
            _sepetim = new hepsiburadaRepositoryFolders.SepetimAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("56b5bbbe-466b-4c6c-bdc1-be13c0197d6b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("2782a6b5-6238-4797-b8c4-6d155dc1a847")]
        public virtual hepsiburadaRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The TuerkiyeninEnBueyuekOnlineAlışveriş folder.
        /// </summary>
        [RepositoryFolder("1422dd9a-5b4f-486f-ac23-1dea4818bb5f")]
        public virtual hepsiburadaRepositoryFolders.TuerkiyeninEnBueyuekOnlineAlışverişAppFolder TuerkiyeninEnBueyuekOnlineAlışveriş
        {
            get { return _tuerkiyeninenbueyuekonlinealışveriş; }
        }

        /// <summary>
        /// The UEyeGirişSayfasıUEyeOlHepsiburad folder.
        /// </summary>
        [RepositoryFolder("3fc094aa-90db-45bb-8532-3e7b393adcb9")]
        public virtual hepsiburadaRepositoryFolders.UEyeGirişSayfasıUEyeOlHepsiburadAppFolder UEyeGirişSayfasıUEyeOlHepsiburad
        {
            get { return _ueyegirişsayfasıueyeolhepsiburad; }
        }

        /// <summary>
        /// The ListemHepsiburada folder.
        /// </summary>
        [RepositoryFolder("31494fcc-6e80-4e19-bc14-e11c39344922")]
        public virtual hepsiburadaRepositoryFolders.ListemHepsiburadaAppFolder ListemHepsiburada
        {
            get { return _listemhepsiburada; }
        }

        /// <summary>
        /// The Sepetim folder.
        /// </summary>
        [RepositoryFolder("9dfa2f09-02a8-4611-ae85-b6833b0180d3")]
        public virtual hepsiburadaRepositoryFolders.SepetimAppFolder Sepetim
        {
            get { return _sepetim; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class hepsiburadaRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("2782a6b5-6238-4797-b8c4-6d155dc1a847")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            hepsiburadaRepositoryFolders.UlTag1Folder _ultag1;
            hepsiburadaRepositoryFolders.MyAccount1Folder _myaccount1;
            RepoItemInfo _eşofmanaltıInfo;
            RepoItemInfo _somespantagInfo;
            RepoItemInfo _somesvgtagInfo;
            RepoItemInfo _httpscheckouthepsiburadacomsepetimInfo;
            RepoItemInfo _beğendiklerimInfo;
            RepoItemInfo _girişyapInfo;
            RepoItemInfo _loginInfo;
            RepoItemInfo _sepeteekleInfo;
            RepoItemInfo _sepeteekle1Info;
            RepoItemInfo _sepeteekle2Info;
            RepoItemInfo _sepeteekle3Info;
            RepoItemInfo _shoppingcartInfo;
            RepoItemInfo _httpscheckouthepsiburadacomsepetim1Info;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.hepsiburada.com']", parentFolder, 30000, null, false, "2782a6b5-6238-4797-b8c4-6d155dc1a847", "")
            {
                _ultag1 = new hepsiburadaRepositoryFolders.UlTag1Folder(this);
                _myaccount1 = new hepsiburadaRepositoryFolders.MyAccount1Folder(this);
                _eşofmanaltıInfo = new RepoItemInfo(this, "EşofmanAltı", ".//div[#'container']/div/div/div[4]/div[3]/div/div//ul/li[6]/div/div/div[1]/div[1]/ul/li/ul[3]/?/?/ul/li/ul[2]/li/a[4]/span[@innertext='Eşofman Altı, ']", ".//div[#'container']//span[@innertext='Eşofman Altı, ']", 30000, null, "948f484a-c1a9-409b-be86-e2aa1a5d955f");
                _somespantagInfo = new RepoItemInfo(this, "SomeSpanTag", "body/div/div/div/div/?/?/div//ul//div/ul/li/ul/li/ul/li/ul//span", "body/div/div/div/div/div/div/div/div/div/div/div/div/div/ul/li/div/div/div/div/ul/li/ul/li/ul/li/ul/li/a/span", 30000, null, "1dd88a61-77d6-4eff-8214-c3e89b8a7d2e");
                _somesvgtagInfo = new RepoItemInfo(this, "SomeSvgTag", ".//div[#'ProductList']/div/div/div/?/?/ul/li[3]/?/?/a[@title>'Nike Dry Parkis Pant.erkek']/div[1]/div[3]/?/?/svg", ".//div[#'ProductList']//svg", 30000, null, "cd7cd475-b9fd-49f6-9f0d-df773453d0b6");
                _httpscheckouthepsiburadacomsepetimInfo = new RepoItemInfo(this, "HttpsCheckoutHepsiburadaComSepetim", "body/div[2]/div[2]/div[1]/div/div/div/div/div/div[2]/div[3]/a[@href>'https://checkout.hepsibur']", ".//a[@href>'https://checkout.hepsibur']", 30000, null, "4bd5ecbd-15a7-4783-afbe-b5f3521f7fcf");
                _beğendiklerimInfo = new RepoItemInfo(this, "Beğendiklerim", ".//div[#'myAccount']//ul/?/?/a[@innertext='Beğendiklerim']", ".//div[#'myAccount']//a[@innertext='Beğendiklerim']", 30000, null, "e96f2f11-bd53-4af4-a78f-db5c943140bb");
                _girişyapInfo = new RepoItemInfo(this, "GirişYap", ".//div[#'myAccount']/?/?/span[@title='Giriş Yap']", ".//div[#'myAccount']/?/?/span[@title='Giriş Yap']", 30000, null, "3426c58c-7af0-4f85-a608-be1879226293");
                _loginInfo = new RepoItemInfo(this, "Login", ".//a[#'login']", ".//a[#'login']", 30000, null, "e0fe1c24-a16a-40c1-9359-4cce0f94678f");
                _sepeteekleInfo = new RepoItemInfo(this, "SepeteEkle", ".//div[#'ProductList']//ul/li[1]/?/?/a[@title>'Nike M Nk Dry PARK20 Pant']/div[2]/div[4]/button/div[@innertext='Sepete ekle']", ".//div[#'ProductList']//div[@innertext='Sepete ekle']", 30000, null, "281bc5c6-5f36-4cac-b180-dac2f4148fcf");
                _sepeteekle1Info = new RepoItemInfo(this, "SepeteEkle1", "body/div[7]/div/div/div/div[2]//button/div[@innertext='Sepete ekle']", ".//div[@innertext='Sepete ekle']", 30000, null, "579c0f09-82cc-44b8-abfd-a98d67a44ff0");
                _sepeteekle2Info = new RepoItemInfo(this, "SepeteEkle2", ".//div[#'ProductList']//ul/li[2]/?/?/a[@title>'Nike M NK DRY PARK18 PANT']/div[2]/div[4]/button/div[@innertext='Sepete ekle']", ".//div[#'ProductList']//div[@innertext='Sepete ekle']", 30000, null, "d26c341c-00d5-461f-81f7-dba97155ab2b");
                _sepeteekle3Info = new RepoItemInfo(this, "SepeteEkle3", "body/div[8]/div/div/div/div[2]//button/div[@innertext='Sepete ekle']", ".//div[@innertext='Sepete ekle']", 30000, null, "2625582d-af35-49ed-8576-c5235ae60e27");
                _shoppingcartInfo = new RepoItemInfo(this, "ShoppingCart", ".//span[#'shoppingCart']", ".//span[#'shoppingCart']", 30000, null, "c41abf5a-5ee9-4206-95da-19016f7d1c2e");
                _httpscheckouthepsiburadacomsepetim1Info = new RepoItemInfo(this, "HttpsCheckoutHepsiburadaComSepetim1", ".//div[#'container']/div/div/div[3]/div[4]/div/div/div/div/div[2]/div[3]/a[@href>'https://checkout.hepsibur']", ".//div[#'container']//a[@href>'https://checkout.hepsibur']", 30000, null, "1ccbeec8-e641-405c-93e6-cc78e4928634");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2782a6b5-6238-4797-b8c4-6d155dc1a847")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2782a6b5-6238-4797-b8c4-6d155dc1a847")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EşofmanAltı item.
            /// </summary>
            [RepositoryItem("948f484a-c1a9-409b-be86-e2aa1a5d955f")]
            public virtual Ranorex.SpanTag EşofmanAltı
            {
                get
                {
                    return _eşofmanaltıInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The EşofmanAltı item info.
            /// </summary>
            [RepositoryItemInfo("948f484a-c1a9-409b-be86-e2aa1a5d955f")]
            public virtual RepoItemInfo EşofmanAltıInfo
            {
                get
                {
                    return _eşofmanaltıInfo;
                }
            }

            /// <summary>
            /// The SomeSpanTag item.
            /// </summary>
            [RepositoryItem("1dd88a61-77d6-4eff-8214-c3e89b8a7d2e")]
            public virtual Ranorex.SpanTag SomeSpanTag
            {
                get
                {
                    return _somespantagInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SomeSpanTag item info.
            /// </summary>
            [RepositoryItemInfo("1dd88a61-77d6-4eff-8214-c3e89b8a7d2e")]
            public virtual RepoItemInfo SomeSpanTagInfo
            {
                get
                {
                    return _somespantagInfo;
                }
            }

            /// <summary>
            /// The SomeSvgTag item.
            /// </summary>
            [RepositoryItem("cd7cd475-b9fd-49f6-9f0d-df773453d0b6")]
            public virtual Ranorex.SvgTag SomeSvgTag
            {
                get
                {
                    return _somesvgtagInfo.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The SomeSvgTag item info.
            /// </summary>
            [RepositoryItemInfo("cd7cd475-b9fd-49f6-9f0d-df773453d0b6")]
            public virtual RepoItemInfo SomeSvgTagInfo
            {
                get
                {
                    return _somesvgtagInfo;
                }
            }

            /// <summary>
            /// The HttpsCheckoutHepsiburadaComSepetim item.
            /// </summary>
            [RepositoryItem("4bd5ecbd-15a7-4783-afbe-b5f3521f7fcf")]
            public virtual Ranorex.ATag HttpsCheckoutHepsiburadaComSepetim
            {
                get
                {
                    return _httpscheckouthepsiburadacomsepetimInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HttpsCheckoutHepsiburadaComSepetim item info.
            /// </summary>
            [RepositoryItemInfo("4bd5ecbd-15a7-4783-afbe-b5f3521f7fcf")]
            public virtual RepoItemInfo HttpsCheckoutHepsiburadaComSepetimInfo
            {
                get
                {
                    return _httpscheckouthepsiburadacomsepetimInfo;
                }
            }

            /// <summary>
            /// The Beğendiklerim item.
            /// </summary>
            [RepositoryItem("e96f2f11-bd53-4af4-a78f-db5c943140bb")]
            public virtual Ranorex.ATag Beğendiklerim
            {
                get
                {
                    return _beğendiklerimInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Beğendiklerim item info.
            /// </summary>
            [RepositoryItemInfo("e96f2f11-bd53-4af4-a78f-db5c943140bb")]
            public virtual RepoItemInfo BeğendiklerimInfo
            {
                get
                {
                    return _beğendiklerimInfo;
                }
            }

            /// <summary>
            /// The GirişYap item.
            /// </summary>
            [RepositoryItem("3426c58c-7af0-4f85-a608-be1879226293")]
            public virtual Ranorex.SpanTag GirişYap
            {
                get
                {
                    return _girişyapInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap item info.
            /// </summary>
            [RepositoryItemInfo("3426c58c-7af0-4f85-a608-be1879226293")]
            public virtual RepoItemInfo GirişYapInfo
            {
                get
                {
                    return _girişyapInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("e0fe1c24-a16a-40c1-9359-4cce0f94678f")]
            public virtual Ranorex.ATag Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("e0fe1c24-a16a-40c1-9359-4cce0f94678f")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The SepeteEkle item.
            /// </summary>
            [RepositoryItem("281bc5c6-5f36-4cac-b180-dac2f4148fcf")]
            public virtual Ranorex.DivTag SepeteEkle
            {
                get
                {
                    return _sepeteekleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle item info.
            /// </summary>
            [RepositoryItemInfo("281bc5c6-5f36-4cac-b180-dac2f4148fcf")]
            public virtual RepoItemInfo SepeteEkleInfo
            {
                get
                {
                    return _sepeteekleInfo;
                }
            }

            /// <summary>
            /// The SepeteEkle1 item.
            /// </summary>
            [RepositoryItem("579c0f09-82cc-44b8-abfd-a98d67a44ff0")]
            public virtual Ranorex.DivTag SepeteEkle1
            {
                get
                {
                    return _sepeteekle1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle1 item info.
            /// </summary>
            [RepositoryItemInfo("579c0f09-82cc-44b8-abfd-a98d67a44ff0")]
            public virtual RepoItemInfo SepeteEkle1Info
            {
                get
                {
                    return _sepeteekle1Info;
                }
            }

            /// <summary>
            /// The SepeteEkle2 item.
            /// </summary>
            [RepositoryItem("d26c341c-00d5-461f-81f7-dba97155ab2b")]
            public virtual Ranorex.DivTag SepeteEkle2
            {
                get
                {
                    return _sepeteekle2Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle2 item info.
            /// </summary>
            [RepositoryItemInfo("d26c341c-00d5-461f-81f7-dba97155ab2b")]
            public virtual RepoItemInfo SepeteEkle2Info
            {
                get
                {
                    return _sepeteekle2Info;
                }
            }

            /// <summary>
            /// The SepeteEkle3 item.
            /// </summary>
            [RepositoryItem("2625582d-af35-49ed-8576-c5235ae60e27")]
            public virtual Ranorex.DivTag SepeteEkle3
            {
                get
                {
                    return _sepeteekle3Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle3 item info.
            /// </summary>
            [RepositoryItemInfo("2625582d-af35-49ed-8576-c5235ae60e27")]
            public virtual RepoItemInfo SepeteEkle3Info
            {
                get
                {
                    return _sepeteekle3Info;
                }
            }

            /// <summary>
            /// The ShoppingCart item.
            /// </summary>
            [RepositoryItem("c41abf5a-5ee9-4206-95da-19016f7d1c2e")]
            public virtual Ranorex.SpanTag ShoppingCart
            {
                get
                {
                    return _shoppingcartInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ShoppingCart item info.
            /// </summary>
            [RepositoryItemInfo("c41abf5a-5ee9-4206-95da-19016f7d1c2e")]
            public virtual RepoItemInfo ShoppingCartInfo
            {
                get
                {
                    return _shoppingcartInfo;
                }
            }

            /// <summary>
            /// The HttpsCheckoutHepsiburadaComSepetim1 item.
            /// </summary>
            [RepositoryItem("1ccbeec8-e641-405c-93e6-cc78e4928634")]
            public virtual Ranorex.ATag HttpsCheckoutHepsiburadaComSepetim1
            {
                get
                {
                    return _httpscheckouthepsiburadacomsepetim1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HttpsCheckoutHepsiburadaComSepetim1 item info.
            /// </summary>
            [RepositoryItemInfo("1ccbeec8-e641-405c-93e6-cc78e4928634")]
            public virtual RepoItemInfo HttpsCheckoutHepsiburadaComSepetim1Info
            {
                get
                {
                    return _httpscheckouthepsiburadacomsepetim1Info;
                }
            }

            /// <summary>
            /// The UlTag1 folder.
            /// </summary>
            [RepositoryFolder("cb3ec88f-0712-40a3-8713-2c9ed20d7dd2")]
            public virtual hepsiburadaRepositoryFolders.UlTag1Folder UlTag1
            {
                get { return _ultag1; }
            }

            /// <summary>
            /// The MyAccount1 folder.
            /// </summary>
            [RepositoryFolder("d53e846e-6fe5-4737-be7c-1e957cf5a40d")]
            public virtual hepsiburadaRepositoryFolders.MyAccount1Folder MyAccount1
            {
                get { return _myaccount1; }
            }
        }

        /// <summary>
        /// The UlTag1Folder folder.
        /// </summary>
        [RepositoryFolder("cb3ec88f-0712-40a3-8713-2c9ed20d7dd2")]
        public partial class UlTag1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _somesvgtag1Info;
            RepoItemInfo _somesvgtag2Info;
            RepoItemInfo _somepathtagInfo;
            RepoItemInfo _somesvgtag3Info;
            RepoItemInfo _somepathtag1Info;

            /// <summary>
            /// Creates a new UlTag1  folder.
            /// </summary>
            public UlTag1Folder(RepoGenBaseFolder parentFolder) :
                    base("UlTag1", ".//div[#'ProductList']/div/div/div/?/?/ul", parentFolder, 30000, null, false, "cb3ec88f-0712-40a3-8713-2c9ed20d7dd2", "")
            {
                _somesvgtag1Info = new RepoItemInfo(this, "SomeSvgTag1", "li[2]/?/?/a[@title>'Hummel Samuel Erkek Tişört']/div[1]/div[3]/?/?/svg", "", 30000, null, "721d5e71-fdd1-4eb4-944e-215511ccfef4");
                _somesvgtag2Info = new RepoItemInfo(this, "SomeSvgTag2", "li[2]/?/?/a[@title>'Hummel Samuel Erkek Tişört']/div[1]/div[3]/div/svg", "", 30000, null, "6671320f-0a63-4552-8ff4-96ae31ff2e21");
                _somepathtagInfo = new RepoItemInfo(this, "SomePathTag", "li[3]/?/?/a[@title>'Hummel Dean Erkek Tişört']/div[1]/div[3]//g/g/path", "g/g/path", 30000, null, "f7300654-9cda-4609-a9eb-81241c5cf063");
                _somesvgtag3Info = new RepoItemInfo(this, "SomeSvgTag3", "li[3]/?/?/a[@title>'Hummel Dean Erkek Tişört']/div[1]/div[3]/?/?/svg", "", 30000, null, "c691f7ff-8252-450a-a097-8b4be4e31042");
                _somepathtag1Info = new RepoItemInfo(this, "SomePathTag1", "li[3]/?/?/a[@title>'Hummel Dean Erkek Tişört']/div[1]/div[3]/div/svg/g/g/path", "g/g/path", 30000, null, "bc646808-42a7-4eb3-80a1-54e6188fecac");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cb3ec88f-0712-40a3-8713-2c9ed20d7dd2")]
            public virtual Ranorex.UlTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cb3ec88f-0712-40a3-8713-2c9ed20d7dd2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeSvgTag1 item.
            /// </summary>
            [RepositoryItem("721d5e71-fdd1-4eb4-944e-215511ccfef4")]
            public virtual Ranorex.SvgTag SomeSvgTag1
            {
                get
                {
                    return _somesvgtag1Info.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The SomeSvgTag1 item info.
            /// </summary>
            [RepositoryItemInfo("721d5e71-fdd1-4eb4-944e-215511ccfef4")]
            public virtual RepoItemInfo SomeSvgTag1Info
            {
                get
                {
                    return _somesvgtag1Info;
                }
            }

            /// <summary>
            /// The SomeSvgTag2 item.
            /// </summary>
            [RepositoryItem("6671320f-0a63-4552-8ff4-96ae31ff2e21")]
            public virtual Ranorex.SvgTag SomeSvgTag2
            {
                get
                {
                    return _somesvgtag2Info.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The SomeSvgTag2 item info.
            /// </summary>
            [RepositoryItemInfo("6671320f-0a63-4552-8ff4-96ae31ff2e21")]
            public virtual RepoItemInfo SomeSvgTag2Info
            {
                get
                {
                    return _somesvgtag2Info;
                }
            }

            /// <summary>
            /// The SomePathTag item.
            /// </summary>
            [RepositoryItem("f7300654-9cda-4609-a9eb-81241c5cf063")]
            public virtual Ranorex.PathTag SomePathTag
            {
                get
                {
                    return _somepathtagInfo.CreateAdapter<Ranorex.PathTag>(true);
                }
            }

            /// <summary>
            /// The SomePathTag item info.
            /// </summary>
            [RepositoryItemInfo("f7300654-9cda-4609-a9eb-81241c5cf063")]
            public virtual RepoItemInfo SomePathTagInfo
            {
                get
                {
                    return _somepathtagInfo;
                }
            }

            /// <summary>
            /// The SomeSvgTag3 item.
            /// </summary>
            [RepositoryItem("c691f7ff-8252-450a-a097-8b4be4e31042")]
            public virtual Ranorex.SvgTag SomeSvgTag3
            {
                get
                {
                    return _somesvgtag3Info.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The SomeSvgTag3 item info.
            /// </summary>
            [RepositoryItemInfo("c691f7ff-8252-450a-a097-8b4be4e31042")]
            public virtual RepoItemInfo SomeSvgTag3Info
            {
                get
                {
                    return _somesvgtag3Info;
                }
            }

            /// <summary>
            /// The SomePathTag1 item.
            /// </summary>
            [RepositoryItem("bc646808-42a7-4eb3-80a1-54e6188fecac")]
            public virtual Ranorex.PathTag SomePathTag1
            {
                get
                {
                    return _somepathtag1Info.CreateAdapter<Ranorex.PathTag>(true);
                }
            }

            /// <summary>
            /// The SomePathTag1 item info.
            /// </summary>
            [RepositoryItemInfo("bc646808-42a7-4eb3-80a1-54e6188fecac")]
            public virtual RepoItemInfo SomePathTag1Info
            {
                get
                {
                    return _somepathtag1Info;
                }
            }
        }

        /// <summary>
        /// The MyAccount1Folder folder.
        /// </summary>
        [RepositoryFolder("d53e846e-6fe5-4737-be7c-1e957cf5a40d")]
        public partial class MyAccount1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _myaccountInfo;
            RepoItemInfo _hkmblueInfo;
            RepoItemInfo _cıkışyapInfo;

            /// <summary>
            /// Creates a new MyAccount1  folder.
            /// </summary>
            public MyAccount1Folder(RepoGenBaseFolder parentFolder) :
                    base("MyAccount1", ".//div[#'myAccount']", parentFolder, 30000, null, false, "d53e846e-6fe5-4737-be7c-1e957cf5a40d", "")
            {
                _myaccountInfo = new RepoItemInfo(this, "MyAccount", "", "", 30000, null, "88735bfd-307a-4bd4-a045-980fd42592ba");
                _hkmblueInfo = new RepoItemInfo(this, "HkmBlue", ".//span[@innertext='Hkm Blue']", ".//span[@innertext='Hkm Blue']", 30000, null, "e6010385-6683-4856-b087-10851d94c29b");
                _cıkışyapInfo = new RepoItemInfo(this, "CıkışYap", ".//ul/?/?/a[@innertext='Çıkış Yap']", ".//a[@innertext='Çıkış Yap']", 30000, null, "37ba5ab6-8830-4c2d-a58f-55d6b1d8b6d8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d53e846e-6fe5-4737-be7c-1e957cf5a40d")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d53e846e-6fe5-4737-be7c-1e957cf5a40d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MyAccount item.
            /// </summary>
            [RepositoryItem("88735bfd-307a-4bd4-a045-980fd42592ba")]
            public virtual Ranorex.DivTag MyAccount
            {
                get
                {
                    return _myaccountInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MyAccount item info.
            /// </summary>
            [RepositoryItemInfo("88735bfd-307a-4bd4-a045-980fd42592ba")]
            public virtual RepoItemInfo MyAccountInfo
            {
                get
                {
                    return _myaccountInfo;
                }
            }

            /// <summary>
            /// The HkmBlue item.
            /// </summary>
            [RepositoryItem("e6010385-6683-4856-b087-10851d94c29b")]
            public virtual Ranorex.SpanTag HkmBlue
            {
                get
                {
                    return _hkmblueInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The HkmBlue item info.
            /// </summary>
            [RepositoryItemInfo("e6010385-6683-4856-b087-10851d94c29b")]
            public virtual RepoItemInfo HkmBlueInfo
            {
                get
                {
                    return _hkmblueInfo;
                }
            }

            /// <summary>
            /// The CıkışYap item.
            /// </summary>
            [RepositoryItem("37ba5ab6-8830-4c2d-a58f-55d6b1d8b6d8")]
            public virtual Ranorex.ATag CıkışYap
            {
                get
                {
                    return _cıkışyapInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The CıkışYap item info.
            /// </summary>
            [RepositoryItemInfo("37ba5ab6-8830-4c2d-a58f-55d6b1d8b6d8")]
            public virtual RepoItemInfo CıkışYapInfo
            {
                get
                {
                    return _cıkışyapInfo;
                }
            }
        }

        /// <summary>
        /// The TuerkiyeninEnBueyuekOnlineAlışverişAppFolder folder.
        /// </summary>
        [RepositoryFolder("1422dd9a-5b4f-486f-ac23-1dea4818bb5f")]
        public partial class TuerkiyeninEnBueyuekOnlineAlışverişAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nativeviewhostInfo;
            RepoItemInfo _focusringInfo;

            /// <summary>
            /// Creates a new TuerkiyeninEnBueyuekOnlineAlışveriş  folder.
            /// </summary>
            public TuerkiyeninEnBueyuekOnlineAlışverişAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TuerkiyeninEnBueyuekOnlineAlışveriş", "/form[@title>'Türkiye''nin En Büyük Online']", parentFolder, 30000, null, true, "1422dd9a-5b4f-486f-ac23-1dea4818bb5f", "")
            {
                _nativeviewhostInfo = new RepoItemInfo(this, "NativeViewHost", "container[@name>'Türkiye''nin En Büyük Online']/container[@name='Microsoft Edge']/?/?/container[@classname='BrowserView']/container[3]//text[@automationid='view_1052']/container[@classname='NativeViewHost']", ".//text[@automationid='view_1052']/container[@classname='NativeViewHost']", 30000, null, "03c1c51d-918a-4763-b6d9-5eb9a0621ec6");
                _focusringInfo = new RepoItemInfo(this, "FocusRing", "container[@name>'Türkiye''nin En Büyük Online']//button[@automationid='view_3']/container[@classname='FocusRing']", ".//button[@automationid='view_3']/container[@classname='FocusRing']", 30000, null, "18cdc563-5632-4622-b392-4ec6d5226353");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1422dd9a-5b4f-486f-ac23-1dea4818bb5f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1422dd9a-5b4f-486f-ac23-1dea4818bb5f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NativeViewHost item.
            /// </summary>
            [RepositoryItem("03c1c51d-918a-4763-b6d9-5eb9a0621ec6")]
            public virtual Ranorex.Container NativeViewHost
            {
                get
                {
                    return _nativeviewhostInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The NativeViewHost item info.
            /// </summary>
            [RepositoryItemInfo("03c1c51d-918a-4763-b6d9-5eb9a0621ec6")]
            public virtual RepoItemInfo NativeViewHostInfo
            {
                get
                {
                    return _nativeviewhostInfo;
                }
            }

            /// <summary>
            /// The FocusRing item.
            /// </summary>
            [RepositoryItem("18cdc563-5632-4622-b392-4ec6d5226353")]
            public virtual Ranorex.Container FocusRing
            {
                get
                {
                    return _focusringInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The FocusRing item info.
            /// </summary>
            [RepositoryItemInfo("18cdc563-5632-4622-b392-4ec6d5226353")]
            public virtual RepoItemInfo FocusRingInfo
            {
                get
                {
                    return _focusringInfo;
                }
            }
        }

        /// <summary>
        /// The UEyeGirişSayfasıUEyeOlHepsiburadAppFolder folder.
        /// </summary>
        [RepositoryFolder("3fc094aa-90db-45bb-8532-3e7b393adcb9")]
        public partial class UEyeGirişSayfasıUEyeOlHepsiburadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtemailInfo;
            RepoItemInfo _girişyapInfo;
            RepoItemInfo _txtusernameInfo;
            RepoItemInfo _btnloginInfo;
            RepoItemInfo _txtpasswordInfo;
            RepoItemInfo _btnemailselectInfo;
            RepoItemInfo _cmjtgzhbaxmmesrdbbs9oih0Info;
            RepoItemInfo _falsefalsemmibirtw8hzvtf4bnicy5Info;
            RepoItemInfo _epostaadresiniziveyatelefonnumaranıInfo;

            /// <summary>
            /// Creates a new UEyeGirişSayfasıUEyeOlHepsiburad  folder.
            /// </summary>
            public UEyeGirişSayfasıUEyeOlHepsiburadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UEyeGirişSayfasıUEyeOlHepsiburad", "/dom[@domain='giris.hepsiburada.com']", parentFolder, 30000, null, false, "3fc094aa-90db-45bb-8532-3e7b393adcb9", "")
            {
                _txtemailInfo = new RepoItemInfo(this, "TxtEmail", ".//input[#'txtEmail']", ".//input[#'txtEmail']", 30000, null, "3dbd8220-81b5-4d0a-ba91-8f4a31bff459");
                _girişyapInfo = new RepoItemInfo(this, "GirişYap", ".//div[#'root']/div/div/div[1]/div[2]/div/div/div[2]/div[1]/?/?/div[@innertext='Giriş yap']", ".//div[#'root']//div[@innertext='Giriş yap']", 30000, null, "40975d9e-f0a1-41b9-8092-4fdb3cfce86e");
                _txtusernameInfo = new RepoItemInfo(this, "TxtUserName", ".//input[#'txtUserName']", ".//input[#'txtUserName']", 30000, null, "29bc7996-855f-4c27-a5aa-46a3e0acfae7");
                _btnloginInfo = new RepoItemInfo(this, "BtnLogin", ".//button[#'btnLogin']", ".//button[#'btnLogin']", 30000, null, "bb9f8184-9bb9-486f-8e72-3451ce84ea5f");
                _txtpasswordInfo = new RepoItemInfo(this, "TxtPassword", ".//form[#'frmNewLogin']//input[@id='txtPassword']", ".//input[#'txtPassword']", 30000, null, "f873465a-bdfc-450e-882e-354906800e20");
                _btnemailselectInfo = new RepoItemInfo(this, "BtnEmailSelect", ".//button[#'btnEmailSelect']", ".//button[#'btnEmailSelect']", 30000, null, "50c29e44-520b-46df-9116-08391bb5fd14");
                _cmjtgzhbaxmmesrdbbs9oih0Info = new RepoItemInfo(this, "CmJTGZHbAxmMESrdbbs9oih0", ".//div[#'root']/div/div/div[1]/div[2]/div/div/div[4]/div/div", ".//div[#'root']/div/div/div[1]/div[2]/div/div/div[4]/div/div", 30000, null, "1ff6415a-73f5-4270-9052-408adf7f7861");
                _falsefalsemmibirtw8hzvtf4bnicy5Info = new RepoItemInfo(this, "FalseFalseMMIbirtW8HZVTf4bniCY5", ".//div[#'root']/div/div/div[1]/div[2]/div", ".//div[#'root']/div/div/div[1]/div[2]/div", 30000, null, "0d4d33d3-883a-4345-aa54-abf6a57f1c79");
                _epostaadresiniziveyatelefonnumaranıInfo = new RepoItemInfo(this, "EPostaAdresiniziVeyaTelefonNumaranı", ".//div[#'root']/div/div/div[1]/div[2]/div/div/div[2]/div[2]//form[@action='https://giris.hepsiburada.com/?ReturnUrl=https%3A%2F%2Foauth.hepsiburada.com%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DSPA%26redirect_uri%3Dhttps%253A%252F%252Fwww.hepsiburada.com%252Fuyelik%252Fcallback%26response_type%3Dcode%26scope%3Dopenid%2520profile%26state%3D234fb942745b46c89a003eebaa6b5d98%26code_challenge%3DMpXIb8PWQ4lUo6TBfmVdRTxcOCJQtO6xFH35eK723ms%26code_challenge_method%3DS256%26response_mode%3Dquery%26ActivePage%3DPURE_LOGIN%26oidcReturnUrl%3Dhttps%253A%252F%252Fwww.hepsiburada.com%252F']/div/?/?/div[@innertext>'E-posta adresinizi veya telefon']", ".//div[#'root']//div[@innertext>'E-posta adresinizi veya telefon']", 30000, null, "958ac352-6f6b-419c-9a9e-ad5e976d27d9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3fc094aa-90db-45bb-8532-3e7b393adcb9")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3fc094aa-90db-45bb-8532-3e7b393adcb9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtEmail item.
            /// </summary>
            [RepositoryItem("3dbd8220-81b5-4d0a-ba91-8f4a31bff459")]
            public virtual Ranorex.InputTag TxtEmail
            {
                get
                {
                    return _txtemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtEmail item info.
            /// </summary>
            [RepositoryItemInfo("3dbd8220-81b5-4d0a-ba91-8f4a31bff459")]
            public virtual RepoItemInfo TxtEmailInfo
            {
                get
                {
                    return _txtemailInfo;
                }
            }

            /// <summary>
            /// The GirişYap item.
            /// </summary>
            [RepositoryItem("40975d9e-f0a1-41b9-8092-4fdb3cfce86e")]
            public virtual Ranorex.DivTag GirişYap
            {
                get
                {
                    return _girişyapInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The GirişYap item info.
            /// </summary>
            [RepositoryItemInfo("40975d9e-f0a1-41b9-8092-4fdb3cfce86e")]
            public virtual RepoItemInfo GirişYapInfo
            {
                get
                {
                    return _girişyapInfo;
                }
            }

            /// <summary>
            /// The TxtUserName item.
            /// </summary>
            [RepositoryItem("29bc7996-855f-4c27-a5aa-46a3e0acfae7")]
            public virtual Ranorex.InputTag TxtUserName
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtUserName item info.
            /// </summary>
            [RepositoryItemInfo("29bc7996-855f-4c27-a5aa-46a3e0acfae7")]
            public virtual RepoItemInfo TxtUserNameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }

            /// <summary>
            /// The BtnLogin item.
            /// </summary>
            [RepositoryItem("bb9f8184-9bb9-486f-8e72-3451ce84ea5f")]
            public virtual Ranorex.ButtonTag BtnLogin
            {
                get
                {
                    return _btnloginInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnLogin item info.
            /// </summary>
            [RepositoryItemInfo("bb9f8184-9bb9-486f-8e72-3451ce84ea5f")]
            public virtual RepoItemInfo BtnLoginInfo
            {
                get
                {
                    return _btnloginInfo;
                }
            }

            /// <summary>
            /// The TxtPassword item.
            /// </summary>
            [RepositoryItem("f873465a-bdfc-450e-882e-354906800e20")]
            public virtual Ranorex.InputTag TxtPassword
            {
                get
                {
                    return _txtpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtPassword item info.
            /// </summary>
            [RepositoryItemInfo("f873465a-bdfc-450e-882e-354906800e20")]
            public virtual RepoItemInfo TxtPasswordInfo
            {
                get
                {
                    return _txtpasswordInfo;
                }
            }

            /// <summary>
            /// The BtnEmailSelect item.
            /// </summary>
            [RepositoryItem("50c29e44-520b-46df-9116-08391bb5fd14")]
            public virtual Ranorex.ButtonTag BtnEmailSelect
            {
                get
                {
                    return _btnemailselectInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BtnEmailSelect item info.
            /// </summary>
            [RepositoryItemInfo("50c29e44-520b-46df-9116-08391bb5fd14")]
            public virtual RepoItemInfo BtnEmailSelectInfo
            {
                get
                {
                    return _btnemailselectInfo;
                }
            }

            /// <summary>
            /// The CmJTGZHbAxmMESrdbbs9oih0 item.
            /// </summary>
            [RepositoryItem("1ff6415a-73f5-4270-9052-408adf7f7861")]
            public virtual Ranorex.DivTag CmJTGZHbAxmMESrdbbs9oih0
            {
                get
                {
                    return _cmjtgzhbaxmmesrdbbs9oih0Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CmJTGZHbAxmMESrdbbs9oih0 item info.
            /// </summary>
            [RepositoryItemInfo("1ff6415a-73f5-4270-9052-408adf7f7861")]
            public virtual RepoItemInfo CmJTGZHbAxmMESrdbbs9oih0Info
            {
                get
                {
                    return _cmjtgzhbaxmmesrdbbs9oih0Info;
                }
            }

            /// <summary>
            /// The FalseFalseMMIbirtW8HZVTf4bniCY5 item.
            /// </summary>
            [RepositoryItem("0d4d33d3-883a-4345-aa54-abf6a57f1c79")]
            public virtual Ranorex.DivTag FalseFalseMMIbirtW8HZVTf4bniCY5
            {
                get
                {
                    return _falsefalsemmibirtw8hzvtf4bnicy5Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The FalseFalseMMIbirtW8HZVTf4bniCY5 item info.
            /// </summary>
            [RepositoryItemInfo("0d4d33d3-883a-4345-aa54-abf6a57f1c79")]
            public virtual RepoItemInfo FalseFalseMMIbirtW8HZVTf4bniCY5Info
            {
                get
                {
                    return _falsefalsemmibirtw8hzvtf4bnicy5Info;
                }
            }

            /// <summary>
            /// The EPostaAdresiniziVeyaTelefonNumaranı item.
            /// </summary>
            [RepositoryItem("958ac352-6f6b-419c-9a9e-ad5e976d27d9")]
            public virtual Ranorex.DivTag EPostaAdresiniziVeyaTelefonNumaranı
            {
                get
                {
                    return _epostaadresiniziveyatelefonnumaranıInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The EPostaAdresiniziVeyaTelefonNumaranı item info.
            /// </summary>
            [RepositoryItemInfo("958ac352-6f6b-419c-9a9e-ad5e976d27d9")]
            public virtual RepoItemInfo EPostaAdresiniziVeyaTelefonNumaranıInfo
            {
                get
                {
                    return _epostaadresiniziveyatelefonnumaranıInfo;
                }
            }
        }

        /// <summary>
        /// The ListemHepsiburadaAppFolder folder.
        /// </summary>
        [RepositoryFolder("31494fcc-6e80-4e19-bc14-e11c39344922")]
        public partial class ListemHepsiburadaAppFolder : RepoGenBaseFolder
        {
            hepsiburadaRepositoryFolders.MyListMainFolder _mylistmain;

            /// <summary>
            /// Creates a new ListemHepsiburada  folder.
            /// </summary>
            public ListemHepsiburadaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ListemHepsiburada", "/dom[@domain='listelerim.hepsiburada.com']", parentFolder, 30000, null, false, "31494fcc-6e80-4e19-bc14-e11c39344922", "")
            {
                _mylistmain = new hepsiburadaRepositoryFolders.MyListMainFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("31494fcc-6e80-4e19-bc14-e11c39344922")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("31494fcc-6e80-4e19-bc14-e11c39344922")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MyListMain folder.
            /// </summary>
            [RepositoryFolder("f78105c5-a4ac-4113-b395-9520325653b6")]
            public virtual hepsiburadaRepositoryFolders.MyListMainFolder MyListMain
            {
                get { return _mylistmain; }
            }
        }

        /// <summary>
        /// The MyListMainFolder folder.
        /// </summary>
        [RepositoryFolder("f78105c5-a4ac-4113-b395-9520325653b6")]
        public partial class MyListMainFolder : RepoGenBaseFolder
        {
            RepoItemInfo _sepetimInfo;
            RepoItemInfo _mylistinfoInfo;
            RepoItemInfo _someultagInfo;
            RepoItemInfo _productviewInfo;
            RepoItemInfo _somepathtagInfo;

            /// <summary>
            /// Creates a new MyListMain  folder.
            /// </summary>
            public MyListMainFolder(RepoGenBaseFolder parentFolder) :
                    base("MyListMain", ".//div[#'root']/div/div", parentFolder, 30000, null, false, "f78105c5-a4ac-4113-b395-9520325653b6", "")
            {
                _sepetimInfo = new RepoItemInfo(this, "Sepetim", "div[1]/div[3]/div/div/div/div/div/div/div[4]/div[2]//a[@title='Sepetim']/?/?/span[@innertext='Sepetim']", "", 30000, null, "5cab66cc-d633-40d2-bd3a-5e9a569260d4");
                _mylistinfoInfo = new RepoItemInfo(this, "MyListInfo", "div[2]/div[1]/div[1]/div[2]", "div[2]/div[1]/div[1]/div[2]", 30000, null, "49ecaa34-b809-4171-b4f1-c91ad38f6f8b");
                _someultagInfo = new RepoItemInfo(this, "SomeUlTag", "div[3]/div[2]/div[2]/div[3]/div[2]/?/?/ul", "", 30000, null, "d4b1e8cc-6290-4cfd-8c15-2cd40bca46a9");
                _productviewInfo = new RepoItemInfo(this, "ProductView", "div[3]/div[2]/div[2]/div[3]", "div[3]/div[2]/div[2]/div[3]", 30000, null, "6343d7c8-3b66-4ed0-88c3-aa9bae1c5bfb");
                _somepathtagInfo = new RepoItemInfo(this, "SomePathTag", "div[1]/div[3]/div/div/div/div/div/div/div[1]/?/?/a[@title='Hepsiburada']/?/?/path", "path", 30000, null, "8c81c1b0-bd16-4d7e-82f6-df1430d6307b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f78105c5-a4ac-4113-b395-9520325653b6")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f78105c5-a4ac-4113-b395-9520325653b6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Sepetim item.
            /// </summary>
            [RepositoryItem("5cab66cc-d633-40d2-bd3a-5e9a569260d4")]
            public virtual Ranorex.SpanTag Sepetim
            {
                get
                {
                    return _sepetimInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Sepetim item info.
            /// </summary>
            [RepositoryItemInfo("5cab66cc-d633-40d2-bd3a-5e9a569260d4")]
            public virtual RepoItemInfo SepetimInfo
            {
                get
                {
                    return _sepetimInfo;
                }
            }

            /// <summary>
            /// The MyListInfo item.
            /// </summary>
            [RepositoryItem("49ecaa34-b809-4171-b4f1-c91ad38f6f8b")]
            public virtual Ranorex.DivTag MyListInfo
            {
                get
                {
                    return _mylistinfoInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MyListInfo item info.
            /// </summary>
            [RepositoryItemInfo("49ecaa34-b809-4171-b4f1-c91ad38f6f8b")]
            public virtual RepoItemInfo MyListInfoInfo
            {
                get
                {
                    return _mylistinfoInfo;
                }
            }

            /// <summary>
            /// The SomeUlTag item.
            /// </summary>
            [RepositoryItem("d4b1e8cc-6290-4cfd-8c15-2cd40bca46a9")]
            public virtual Ranorex.UlTag SomeUlTag
            {
                get
                {
                    return _someultagInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The SomeUlTag item info.
            /// </summary>
            [RepositoryItemInfo("d4b1e8cc-6290-4cfd-8c15-2cd40bca46a9")]
            public virtual RepoItemInfo SomeUlTagInfo
            {
                get
                {
                    return _someultagInfo;
                }
            }

            /// <summary>
            /// The ProductView item.
            /// </summary>
            [RepositoryItem("6343d7c8-3b66-4ed0-88c3-aa9bae1c5bfb")]
            public virtual Ranorex.DivTag ProductView
            {
                get
                {
                    return _productviewInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ProductView item info.
            /// </summary>
            [RepositoryItemInfo("6343d7c8-3b66-4ed0-88c3-aa9bae1c5bfb")]
            public virtual RepoItemInfo ProductViewInfo
            {
                get
                {
                    return _productviewInfo;
                }
            }

            /// <summary>
            /// The SomePathTag item.
            /// </summary>
            [RepositoryItem("8c81c1b0-bd16-4d7e-82f6-df1430d6307b")]
            public virtual Ranorex.PathTag SomePathTag
            {
                get
                {
                    return _somepathtagInfo.CreateAdapter<Ranorex.PathTag>(true);
                }
            }

            /// <summary>
            /// The SomePathTag item info.
            /// </summary>
            [RepositoryItemInfo("8c81c1b0-bd16-4d7e-82f6-df1430d6307b")]
            public virtual RepoItemInfo SomePathTagInfo
            {
                get
                {
                    return _somepathtagInfo;
                }
            }
        }

        /// <summary>
        /// The SepetimAppFolder folder.
        /// </summary>
        [RepositoryFolder("9dfa2f09-02a8-4611-ae85-b6833b0180d3")]
        public partial class SepetimAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _sidebarcontent1fieInfo;
            RepoItemInfo _somesvgtagInfo;
            RepoItemInfo _someatagInfo;
            RepoItemInfo _sidebarcontent1fie1Info;
            RepoItemInfo _continuestepbtnInfo;
            RepoItemInfo _somedivtagInfo;
            RepoItemInfo _oedemeInfo;

            /// <summary>
            /// Creates a new Sepetim  folder.
            /// </summary>
            public SepetimAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Sepetim", "/dom[@domain='checkout.hepsiburada.com']", parentFolder, 30000, null, false, "9dfa2f09-02a8-4611-ae85-b6833b0180d3", "")
            {
                _sidebarcontent1fieInfo = new RepoItemInfo(this, "SidebarContent1fiE", ".//div[#'app']/div/div/div[2]/div/div[3]/div/div", ".//div[#'app']/div/div/div[2]/div/div[3]/div/div", 30000, null, "5fe2110e-fb07-4794-aa6e-19679a6788f5");
                _somesvgtagInfo = new RepoItemInfo(this, "SomeSvgTag", ".//div[#'app']/div/div/div[1]/div/div/div/div/div/div/div/div[1]/?/?/a[@title='Hepsiburada']/svg", ".//div[#'app']//a[@title='Hepsiburada']/svg", 30000, null, "3a6f5f38-80dd-4296-93af-238ae869b15b");
                _someatagInfo = new RepoItemInfo(this, "SomeATag", "body/div/div/div/div/div//a", "body/div/div/div/div/div/div/div/div/div/div/div/a", 30000, null, "b203e452-c7c7-4969-bfd1-a6eea2935d39");
                _sidebarcontent1fie1Info = new RepoItemInfo(this, "SidebarContent1fiE1", ".//div[#'app']/div/div/div[1]/div/div[2]/div/div", ".//div[#'app']/div/div/div[1]/div/div[2]/div/div", 30000, null, "fc0f6462-4827-49d9-aa26-216447acb6c2");
                _continuestepbtnInfo = new RepoItemInfo(this, "ContinueStepBtn", ".//button[#'continue_step_btn']", ".//button[#'continue_step_btn']", 30000, null, "3f335c67-ca48-45bc-a44d-d897274fcb04");
                _somedivtagInfo = new RepoItemInfo(this, "SomeDivTag", ".//header[#'checkout_header']/div/div", ".//header[#'checkout_header']/div/div", 30000, null, "824c21d6-8d77-450d-ac86-86845be1eba6");
                _oedemeInfo = new RepoItemInfo(this, "OEdeme", ".//header[#'checkout_header']/div/div/div[2]/a[@innertext='Ödeme']", ".//header[#'checkout_header']//a[@innertext='Ödeme']", 30000, null, "572d825a-281d-48e1-a163-ee63a010e0d4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9dfa2f09-02a8-4611-ae85-b6833b0180d3")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9dfa2f09-02a8-4611-ae85-b6833b0180d3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SidebarContent1fiE item.
            /// </summary>
            [RepositoryItem("5fe2110e-fb07-4794-aa6e-19679a6788f5")]
            public virtual Ranorex.DivTag SidebarContent1fiE
            {
                get
                {
                    return _sidebarcontent1fieInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SidebarContent1fiE item info.
            /// </summary>
            [RepositoryItemInfo("5fe2110e-fb07-4794-aa6e-19679a6788f5")]
            public virtual RepoItemInfo SidebarContent1fiEInfo
            {
                get
                {
                    return _sidebarcontent1fieInfo;
                }
            }

            /// <summary>
            /// The SomeSvgTag item.
            /// </summary>
            [RepositoryItem("3a6f5f38-80dd-4296-93af-238ae869b15b")]
            public virtual Ranorex.SvgTag SomeSvgTag
            {
                get
                {
                    return _somesvgtagInfo.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The SomeSvgTag item info.
            /// </summary>
            [RepositoryItemInfo("3a6f5f38-80dd-4296-93af-238ae869b15b")]
            public virtual RepoItemInfo SomeSvgTagInfo
            {
                get
                {
                    return _somesvgtagInfo;
                }
            }

            /// <summary>
            /// The SomeATag item.
            /// </summary>
            [RepositoryItem("b203e452-c7c7-4969-bfd1-a6eea2935d39")]
            public virtual Ranorex.ATag SomeATag
            {
                get
                {
                    return _someatagInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SomeATag item info.
            /// </summary>
            [RepositoryItemInfo("b203e452-c7c7-4969-bfd1-a6eea2935d39")]
            public virtual RepoItemInfo SomeATagInfo
            {
                get
                {
                    return _someatagInfo;
                }
            }

            /// <summary>
            /// The SidebarContent1fiE1 item.
            /// </summary>
            [RepositoryItem("fc0f6462-4827-49d9-aa26-216447acb6c2")]
            public virtual Ranorex.DivTag SidebarContent1fiE1
            {
                get
                {
                    return _sidebarcontent1fie1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SidebarContent1fiE1 item info.
            /// </summary>
            [RepositoryItemInfo("fc0f6462-4827-49d9-aa26-216447acb6c2")]
            public virtual RepoItemInfo SidebarContent1fiE1Info
            {
                get
                {
                    return _sidebarcontent1fie1Info;
                }
            }

            /// <summary>
            /// The ContinueStepBtn item.
            /// </summary>
            [RepositoryItem("3f335c67-ca48-45bc-a44d-d897274fcb04")]
            public virtual Ranorex.ButtonTag ContinueStepBtn
            {
                get
                {
                    return _continuestepbtnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ContinueStepBtn item info.
            /// </summary>
            [RepositoryItemInfo("3f335c67-ca48-45bc-a44d-d897274fcb04")]
            public virtual RepoItemInfo ContinueStepBtnInfo
            {
                get
                {
                    return _continuestepbtnInfo;
                }
            }

            /// <summary>
            /// The SomeDivTag item.
            /// </summary>
            [RepositoryItem("824c21d6-8d77-450d-ac86-86845be1eba6")]
            public virtual Ranorex.DivTag SomeDivTag
            {
                get
                {
                    return _somedivtagInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SomeDivTag item info.
            /// </summary>
            [RepositoryItemInfo("824c21d6-8d77-450d-ac86-86845be1eba6")]
            public virtual RepoItemInfo SomeDivTagInfo
            {
                get
                {
                    return _somedivtagInfo;
                }
            }

            /// <summary>
            /// The OEdeme item.
            /// </summary>
            [RepositoryItem("572d825a-281d-48e1-a163-ee63a010e0d4")]
            public virtual Ranorex.ATag OEdeme
            {
                get
                {
                    return _oedemeInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The OEdeme item info.
            /// </summary>
            [RepositoryItemInfo("572d825a-281d-48e1-a163-ee63a010e0d4")]
            public virtual RepoItemInfo OEdemeInfo
            {
                get
                {
                    return _oedemeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
