///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace hepsiburada
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The login recording.
    /// </summary>
    [TestModule("6538de22-28bb-4443-9a7c-91997461ede7", ModuleType.Recording, 1)]
    public partial class login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the hepsiburadaRepository repository.
        /// </summary>
        public static hepsiburadaRepository repo = hepsiburadaRepository.Instance;

        static login instance = new login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'TuerkiyeninEnBueyuekOnlineAlışveriş.FocusRing' at 40;0.", repo.TuerkiyeninEnBueyuekOnlineAlışveriş.FocusRingInfo, new RecordItemIndex(0));
            repo.TuerkiyeninEnBueyuekOnlineAlışveriş.FocusRing.MoveTo("40;0");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'TuerkiyeninEnBueyuekOnlineAlışveriş.NativeViewHost' at 1490;91.", repo.TuerkiyeninEnBueyuekOnlineAlışveriş.NativeViewHostInfo, new RecordItemIndex(1));
            repo.TuerkiyeninEnBueyuekOnlineAlışveriş.NativeViewHost.MoveTo("1490;91");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TuerkiyeninEnBueyuekOnlineAlışveriş.NativeViewHost' at 1485;183.", repo.TuerkiyeninEnBueyuekOnlineAlışveriş.NativeViewHostInfo, new RecordItemIndex(2));
            repo.TuerkiyeninEnBueyuekOnlineAlışveriş.NativeViewHost.Click("1485;183");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserName' at 275;42.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserNameInfo, new RecordItemIndex(3));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserName.Click("275;42");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'bluehkm{LControlKey down}{RMenu down}{Qkey}{RMenu up}{LControlKey up}{LControlKey up}gmail.com' with focus on 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserName'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserNameInfo, new RecordItemIndex(4));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserName.PressKeys("bluehkm{LControlKey down}{RMenu down}{Qkey}{RMenu up}{LControlKey up}{LControlKey up}gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UEyeGirişSayfasıUEyeOlHepsiburad.BtnLogin' at 278;36.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.BtnLoginInfo, new RecordItemIndex(5));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.BtnLogin.Click("278;36");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtPassword' at 274;39.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtPasswordInfo, new RecordItemIndex(6));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtPassword.Click("274;39");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Bh' with focus on 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtPassword'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtPasswordInfo, new RecordItemIndex(7));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtPassword.PressKeys("Bh");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '123456' with focus on 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtPassword'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtPasswordInfo, new RecordItemIndex(8));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtPassword.PressKeys("123456");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UEyeGirişSayfasıUEyeOlHepsiburad.BtnEmailSelect' at 271;35.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.BtnEmailSelectInfo, new RecordItemIndex(9));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.BtnEmailSelect.Click("271;35");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
