///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace hepsiburada
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The registerAvailable recording.
    /// </summary>
    [TestModule("2d7c28d1-a825-4830-be21-9a04dce5418a", ModuleType.Recording, 1)]
    public partial class RegisterAvailable : ITestModule
    {
        /// <summary>
        /// Holds an instance of the hepsiburadaRepository repository.
        /// </summary>
        public static hepsiburadaRepository repo = hepsiburadaRepository.Instance;

        static RegisterAvailable instance = new RegisterAvailable();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RegisterAvailable()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RegisterAvailable Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'TuerkiyeninEnBueyuekOnlineAlışveriş.NativeViewHost' at 1498;83.", repo.TuerkiyeninEnBueyuekOnlineAlışveriş.NativeViewHostInfo, new RecordItemIndex(0));
            repo.TuerkiyeninEnBueyuekOnlineAlışveriş.NativeViewHost.MoveTo("1498;83");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'TuerkiyeninEnBueyuekOnlineAlışveriş.NativeViewHost' at 1490;91.", repo.TuerkiyeninEnBueyuekOnlineAlışveriş.NativeViewHostInfo, new RecordItemIndex(1));
            repo.TuerkiyeninEnBueyuekOnlineAlışveriş.NativeViewHost.MoveTo("1490;91");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TuerkiyeninEnBueyuekOnlineAlışveriş.NativeViewHost' at 1485;183.", repo.TuerkiyeninEnBueyuekOnlineAlışveriş.NativeViewHostInfo, new RecordItemIndex(2));
            repo.TuerkiyeninEnBueyuekOnlineAlışveriş.NativeViewHost.Click("1485;183");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtEmail'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtEmailInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtEmailInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtEmail'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtEmailInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtEmailInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='') on item 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtEmail'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtEmailInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtEmailInfo, "InnerText", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='') on item 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtEmail'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtEmailInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtEmailInfo, "Value", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UEyeGirişSayfasıUEyeOlHepsiburad.GirişYap' at 57;22.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.GirişYapInfo, new RecordItemIndex(7));
            repo.UEyeGirişSayfasıUEyeOlHepsiburad.GirişYap.Click("57;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserName'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserNameInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserNameInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='') on item 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserName'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserNameInfo, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserNameInfo, "InnerText", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='') on item 'UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserName'.", repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserNameInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.UEyeGirişSayfasıUEyeOlHepsiburad.TxtUserNameInfo, "Value", "");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
